# 테스트용 설정 (H2 인메모리 데이터베이스 사용)
spring:
  application:
    name: spring-backend-test

  # H2 인메모리 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    show-sql: true

  # Redis 비활성화 (테스트용)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# 로깅 설정
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.iroomclass.springbackend: DEBUG

# AI 서버 설정 (비활성화)
ai:
  server:
    base-url: http://localhost:8000
    connect-timeout: 30
    response-timeout: 60
    max-in-memory-size: 50

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: false

server:
  port: 3055
  servlet:
    context-path: /api