# 서버 설정
server:
  port: 3055

  servlet:
    context-path: /api

spring:
  application:
    name: spring-backend

  # 데이터베이스 연결 설정
  datasource:
    url: jdbc:mysql://project-db-campus.smhrd.com:3307/campus_25SW_FS_p3_4
    username: campus_25SW_FS_p3_4
    password: smhrd4
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[format_sql]": true
        "[use_sql_comments]": true
    open-in-view: false

  # Redis 설정 (캐싱용)
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # 개발 환경 설정
  devtools:
    restart:
      enabled: true

  output:
    ansi:
      enabled: ALWAYS

# 로깅 설정
logging:
  file:
    path: logs
  level:
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[com.iroomclass.spring_backend]": DEBUG

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: false
