# 로컬 테스트용 설정 (H2 인메모리 데이터베이스 사용)
spring:
  # H2 인메모리 데이터베이스
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA 설정 
  jpa:
    hibernate:
      ddl-auto: create-drop  # 테스트용이므로 매번 새로 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 콘솔 활성화 (테스트용)
  h2:
    console:
      enabled: true
      path: /h2-console

# 로깅 설정
logging:
  level:
    "[org.hibernate.SQL]": DEBUG
    "[com.iroomclass.springbackend]": DEBUG
    "[org.springframework.security]": DEBUG
    root: INFO