# 개발 환경 전용 설정
spring:
  jpa:
    # SQL 로깅 활성화
    show-sql: true
    properties:
      hibernate:
        # ========================================
        # 개발 환경 디버깅 설정
        # ========================================
        
        # Hibernate 통계 활성화 (성능 분석용)
        generate_statistics: true
        
        # SQL 로깅 상세 설정
        "[format_sql]": true
        "[use_sql_comments]": true
        "[show_sql]": true
        
        # 느린 쿼리 임계값 낮춤 (500ms)
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 500
        
        # 배치 처리 디버그
        jdbc:
          batch_size: 10  # 개발 환경에서는 작게 설정하여 로그 확인 용이
        
        # ========================================
        # 개발 편의 설정
        # ========================================
        
        # DDL 자동 생성 (개발 환경만)
        hbm2ddl:
          auto: update
        
        # 스키마 검증 로깅
        hbm2ddl:
          charset_name: UTF-8

  # 개발 환경 데이터소스 설정
  datasource:
    hikari:
      # 개발 환경에서는 연결 풀 크기 작게 설정
      maximum-pool-size: 5
      minimum-idle: 2
      # 연결 누수 감지 시간 단축 (3분)
      leak-detection-threshold: 180000

# 개발 환경 로깅 설정
logging:
  level:
    root: INFO
    "[com.iroomclass.springbackend]": DEBUG
    
    # Hibernate 상세 로깅
    "[org.hibernate.SQL]": DEBUG
    "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
    "[org.hibernate.type.descriptor.sql.BasicExtractor]": TRACE
    
    # 통계 로깅
    "[org.hibernate.stat]": DEBUG
    
    # JPA 로깅
    "[org.springframework.orm.jpa]": DEBUG
    
    # 트랜잭션 로깅
    "[org.springframework.transaction]": DEBUG
    
    # 연결 풀 로깅
    "[com.zaxxer.hikari]": DEBUG

# 개발 도구 설정
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans, env, configprops, loggers
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# 개발 환경 성능 모니터링
performance:
  monitoring:
    enabled: true
    thresholds:
      query-time-warning: 500
      query-time-error: 2000
    
  hibernate:
    statistics:
      enabled: true
      log-summary: true